mutex: define empty destructor
I don't think we really need the destructor. It causes undefined
reference compilation errors though:

  ... undefined reference to `std::mutex::~mutex()'